### ISSUE TITLE
bug: essageError: Failed to process message during connection, calling disconnect: Unknown type received: 1 [UnknownType]

### ISSUE THREAD

**Issue by kakarot-dev** [kyranet/veza#321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

If i leave the connection on from some time, it throws this error and shuts the whole process down

### Steps To Reproduce

-

### Expected behavior

No errors

### Screenshots

![image](https://user-images.githubusercontent.com/76399483/153525887-07fda6e9-5ab1-4eda-b311-3b21433c887b.png)

**Comment by legendhimslef** [comment]
found any fixes?
I found the source in binartf, not sure how to fix.
```js
parse error @1:0: 4 (not well-formed (invalid token)).
[ 1080205 ]: | Tue, 19 Jul 2022 00:52:08 | INFO | Manager.log | Worker Disconnected: worker1080220
[ 1080205 ]: | Tue, 19 Jul 2022 00:52:08 | ERROR | Manager.log | Error: Socket has been disconnected.
    at ServerSocket.disconnect (/home/Sofi/node_modules/veza/dist/lib/ServerSocket.js:80:33)
    at ServerSocket._onClose (/home/Sofi/node_modules/veza/dist/lib/ServerSocket.js:115:14)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at TCP.<anonymous> (node:net:709:12)
```

**Comment by kakarot-dev** [comment]
Sorry I did not. I degraded my node version as that was the only thing I could do
